#  file with  deployment, service and ingress

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jetcv-deployment-frontend
  labels:
    app: jetcv-frontend
spec:
  replicas: 6
  selector:
    matchLabels:
      app: jetcv-frontend
  template:
    metadata:
      labels:
        app: jetcv-frontend
    spec:
      containers:
        - name: jetcv-frontend
          image: appwharf/mevfinal:sha-7610d7d
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: jetcv-frontend-service
spec:
  selector:
    app: jetcv-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-jetcv
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
     if ($host = 'www.jetcv.co' ) {
      rewrite ^ https://jetcv.co$request_uri permanent;
     }
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jetcv.co
    - www.jetcv.co
    secretName: jetcv-tls
  rules:
  - host: jetcv.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jetcv-frontend-service
            port:
              number: 3000
  - host: www.jetcv.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jetcv-frontend-service
            port:
              number: 3000