# file with  deployment, service and ingress


apiVersion: apps/v1
kind: Deployment
metadata:
  name: jetcv-backend-deployment
  labels:
    app: jetcv-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jetcv-backend
  template:
    metadata:
      labels:
        app: jetcv-backend
    spec:
      containers:
      - name: jetcv-backend
        image: appwharf/mrbackend:sha-e43d864
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
       

---

apiVersion: v1
kind: Service
metadata:
  name: jetcv-backend-service
spec:
  selector:
    app: jetcv-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-jetcv-backend
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.jetcv.co
    secretName: jetcv-backend-tls
  rules:
  - host: api.jetcv.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jetcv-backend-service
            port:
              number: 8000
      # - path: /og
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: og-image-service
      #       port:
      #         number: 4000        
