#  file with  deployment, service and ingress

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dry-mevvit-deployment-frontend
  labels:
    app: dry-mevvit-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dry-mevvit-frontend
  template:
    metadata:
      labels:
        app: dry-mevvit-frontend
    spec:
      containers:
        - name: dry-mevvit-frontend
          image: appwharf/mevfinal:sha-ac9218a
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: dry-mevvit-frontend-service
spec:
  selector:
    app: dry-mevvit-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mevvit
  annotations:
    # nginx.ingress.kubernetes.io/affinity: "cookie"
    # nginx.ingress.kubernetes.io/session-cookie-name: "route"
    # nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    # nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dry.mevvit.com
    secretName: mevvit-frontend-tls
  rules:
  - host: dry.mevvit.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dry-mevvit-frontend-service
            port:
              number: 3000
